### PR TITLE
Enhancement - enabled particle rotations

### PR DESCRIPTION
**Pull request by andrewleek-droplab**
This PR should close this issue: https://github.com/creativelifeform/three-nebula/issues/64

I have added support for both the SpriteRenderer & the GPURenderer.
I have also made a sandbox test to visualize it.

### CODE REVIEW

**Review by manthrax — APPROVED** [review]
sweet!

**Comment by rohan-deshpande** [comment]
@andrewleek-droplab if you could fix this failing test that'd be super sweet. If you can't find a quick fix for it, just `.skip` the test and I'll get to it later, I'll need to release this as a major anyway as it changes existing `SpriteRenderer` functionality.

**Comment by andrewleek-droplab** [comment]
> @andrewleek-droplab if you could fix this failing test that'd be super sweet. If you can't find a quick fix for it, just `.skip` the test and I'll get to it later, I'll need to release this as a major anyway as it changes existing `SpriteRenderer` functionality.

Pardon the delay, Ive been wrapped up in a project the past week.  I have pushed up a fix for that failing test.  So we should be good to go.

**Comment by andrewleek-droplab** [comment]
@rohan-deshpande Looks like merging is still blocked on this... anything to be done on my end?

**Comment by rohan-deshpande** [comment]
@andrewleek-droplab No, this is a github actions bug imo, I removed the `10x` pipeline ages ago, I don't know why it's still there. Have been very busy with life, I will try to get these merged this weekend sorry for the delay.

**Pull request merged**
