### PR TITLE
Bug Fix: allow emitted particles to live out their lives on stopEmit()

### PR DESCRIPTION
**Pull request by andrewleek-droplab**
This fixes a bug where emitted particles would stop animating when calling stopEmit() on an emitter.  Now they will live out the rest of their life cycle completely.

This should close this issue: https://github.com/creativelifeform/three-nebula/issues/169

I also built a sandbox example to illustrate/test this, and it seems to work fine with both the gpu-renderer and the sprite-renderer.

### CODE REVIEW

**Comment by rohan-deshpande** [comment]
Some builds are failing, I'll check this out tonight and see what's going on, seems to be prettier stuff

**Comment by andrewleek-droplab** [comment]
> Some builds are failing, I'll check this out tonight and see what's going on, seems to be prettier stuff

Hey @rohan-deshpande 

I went ahead and fixed up those prettier issues ... sorry about that.  Actually, I think my git-fu needs some work, as I assumed a PR was frozen in time with regards the file's changed at that moment of request.  These prettier errors are due to some newer changes I pushed up after (which i was also planning on doing a PR for).  These new changes are in regards to keeping the GPU particle size consistent and relative to the size fo the canvas height.  This fixes issues on devices with different device pixel ratios as well as general scaling of canvas'.

I have been testing this and it seems to be working fine but I did have to touch a lot of files to get things setup correctly, so probably best to review these to make sure they dont have any issues.

Im guessing I should be putting features into branches and then doing PR's on those, correct?

**Comment by andrewleek-droplab** [comment]
@rohan-deshpande

Please let me know if i should close this PR and separate changes into their own branches to make new PR's.

**Comment by andrewleek-droplab** [comment]
@rohan-deshpande

I realized it was indeed the best course of action to do this PR from its own branch and have done just this with: https://github.com/creativelifeform/three-nebula/pull/208

Closing this one... and pardon the user error.  Lovely library btw!!

**Pull request closed without merging**
